"""Generate runnable notebook shells and source documentation from the implemented APIs."""
from pathlib import Path
import nbformat as nbf

ROOT=Path(__file__).resolve().parents[1]
NB=ROOT/"notebooks"; DOC=ROOT/"docs"
notebooks=[("01_Data_Exploration","Data exploration","from src.data_processing.data_validator import load_news_dataset, DatasetValidator\ndf=load_news_dataset()\nDatasetValidator().validate(df).to_dict()"),("02_Advanced_Classification","Advanced classification","from src.analysis.classifier import AdvancedNewsClassifier\nfrom src.data_processing.data_validator import load_news_dataset\ndf=load_news_dataset(); model=AdvancedNewsClassifier().fit(df.full_text,df.category); model.evaluation_results"),("03_Topic_Modeling","LDA and NMF topic modeling","from src.analysis.topic_modeler import TopicDiscoveryEngine\nfrom src.data_processing.data_validator import load_news_dataset\ndf=load_news_dataset(); topics=TopicDiscoveryEngine().fit_topics(df.full_text,df.date); topics.compare_models()"),("04_Language_Models","Summarization and semantic search","from src.language_models import IntelligentSummarizer, SemanticSearchEngine\nsummary=IntelligentSummarizer().summarize_article('The city announced a new public health plan. Officials said it starts next week.'); summary"),("05_Multilingual_Analysis","Multilingual demonstration","import json\nfrom src.multilingual import LanguageDetector, Translator\ndemo=json.load(open('data/demo/multilingual_demo.json')); [(x['id'],LanguageDetector().detect_language(x['text'])) for x in demo]"),("06_Conversational_Interface","Grounded conversational interface","from src.system import NewsBot2IntegratedSystem\nsystem=NewsBot2IntegratedSystem().fit(); system.query_interface('Show me tech news')"),("07_System_Integration","Integrated NewsBot 2.0 capstone","from src.system import NewsBot2IntegratedSystem\nsystem=NewsBot2IntegratedSystem().fit(); system.comprehensive_analysis('A software company announced an artificial intelligence product in California.')")]
for stem,title,code in notebooks:
 n=nbf.v4.new_notebook(); n.cells=[nbf.v4.new_markdown_cell(f"# NewsBot 2.0 — {title}\n\nThis notebook imports reusable `src/` modules. Run it from the repository root after installing requirements."),nbf.v4.new_code_cell(code),nbf.v4.new_markdown_cell("## Limitations and ethics\nThe corpus is historical and predominantly English. Model confidence is not truth; sentiment, NER, translation, and semantic similarity can be wrong. Internal corroboration is not fact-checking.")]; nbf.write(n,NB/f"{stem}.ipynb")
docs={
"technical_documentation.md":"# Technical Documentation\n\n## Architecture\nNewsBot 2.0 refactors the completed midterm’s deterministic HuffPost sampling, NLTK preprocessing, TF-IDF comparison, VADER sentiment, spaCy NER, evaluation, and visualizations into modules. New layers add LDA/NMF, topic trends, graph construction, lazy transformer summarization, semantic search, multilingual demo processing, and grounded conversation.\n\n## Data flow\nCSV → validation/normalization → preprocessing → classifier/topic/sentiment/NER/search → integrated JSON report. Components fail independently and return warnings.\n\n## Evaluation and limits\nSee `data/results/metrics`. The main corpus is historical English headline/description text, not full articles. Confidence is not truth and graph co-occurrence is not a real-world relationship.\n\n## Security\nEnvironment variables hold secrets. No raw dataset, model cache, or `.env` is committed.",
"executive_summary.md":"# Executive Summary\n\nNewsBot 2.0 helps editors and analysts route historical news coverage, inspect themes and tone, find related items, and query the local corpus. Potential value is reduced first-pass review time; ROI is an assumption: `(hours saved × loaded hourly cost) − operating cost`, not an audited result. It should support—not replace—editorial judgment.\n\nRecommendation: use as a transparent research and triage companion, with human review for low-confidence, sensitive, multilingual, or factual claims.",
"user_guide.md":"# User Guide\n\nRun `./.venv/bin/python run.py` for the local service or open notebooks in order. Paste article text for analysis; confidence is a routing score, not proof. Use queries such as `Show me tech news`, then `What about negative ones?`; dates are relative to the historical dataset maximum where relevant. Multilingual examples live in `data/demo`.\n\nTroubleshooting: install requirements, download `en_core_web_sm`, and expect first-run optional model downloads only when explicitly enabled.",
"api_reference.md":"# API Reference\n\n`AdvancedNewsClassifier`: fit, predict, predict_with_confidence, explain_prediction, evaluate, save/load. `TopicDiscoveryEngine`: fit_topics, get_topic_words, get_article_topics, compare_models, track_topic_trends. `SentimentEvolutionTracker`: analyze, track_sentiment_over_time, detect_sentiment_anomalies. `EntityRelationshipMapper`: extract_entities, extract_relationships, build_knowledge_graph. `NewsBot2IntegratedSystem`: fit, comprehensive_analysis, batch_analysis, query_interface, generate_insights_report.",
"deployment_guide.md":"# Deployment Guide\n\n```bash\npython3 -m venv .venv\n.venv/bin/pip install -r requirements.txt\n.venv/bin/python -m spacy download en_core_web_sm\n.venv/bin/python -m pytest -q\n```\n\nUse CPU PyTorch by default. `gunicorn 'web.app:create_app()'` serves the optional Flask UI. Set `NEWSBOT_SECRET_KEY`; debug is off by default. `/health` is the deployment health check.",
"individual_contributions.md":"# Individual Contributions\n\nJason Trimble: extended the completed NewsBot architecture, data pipeline, model evaluation, integrated NLP modules, tests, documentation, and local deployment assets.\n\nTODO: Confirm group name and teammate contribution details before final submission.",
"ai_assistance.md":"# AI Assistance Disclosure\n\nAI assistance supported planning, debugging, documentation, and implementation iteration. Final code was tested locally. External packages/models are documented in requirements; outputs requiring external models or translation are not presented as independently verified facts.",
"reflective_journal_draft.md":"# Reflective Journal Draft\n\nThis project evolved a notebook prototype into a modular system. The main challenge was preserving a reproducible midterm pipeline while adding heavier components without making local operation fragile. I learned to prefer transparent fallbacks, measured comparisons, error isolation, and honest limits over impressive but unreliable claims.\n\nThe business value is faster exploration of historical coverage, not automatic editorial truth. Ethical risks include source bias, historical drift, sentiment/NER errors, translation loss, privacy when adapted to private documents, and false confidence. Future work includes human evaluation, stronger multilingual benchmark data, and a carefully scoped transformer study.\n\nTODO: Confirm group name and teammate collaboration details before submission.",
"presentation_outline.md":"# Presentation Outline\n\n1 Title · 2 business problem · 3 midterm to final evolution · 4 architecture · 5 dataset · 6 classification · 7 topics · 8 sentiment/entities · 9 language models · 10 multilingual demo · 11 conversation · 12 integrated demo · 13 evaluation · 14 business value · 15 limitations/ethics · 16 contribution/Q&A.\n\nDemo: run one article analysis, search Tech coverage, show a follow-up, then explain that all results are historical local-corpus evidence.",
"references.md":"# References\n\nHuffPost News Category Dataset; scikit-learn, spaCy, VADER Sentiment, Sentence-Transformers, Hugging Face Transformers, Flask documentation. Cite package/model pages in final PDF exports."
}
for name,body in docs.items(): (DOC/name).write_text(body+"\n",encoding="utf-8")
print("Generated notebooks and documentation sources.")
